project:
  type: website
  output-dir: docs

website:
  title: "Mi blog :)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual
from: markdown+emoji

